services:
  app:
    image: node:22-bullseye-slim
    working_dir: /workspace
    volumes:
      - ../:/workspace:cached
      - node_modules:/workspace/node_modules
    command: sleep infinity
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
      - upstash-redis
    networks:
      - development

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - development

  upstash-redis:
    image: hiett/serverless-redis-http:latest
    restart: unless-stopped
    ports:
      - "8079:80"
    environment:
      - SRH_MODE=env
      - SRH_TOKEN=local-dev-token
      - SRH_CONNECTION_STRING=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - development

volumes:
  node_modules:
  redis_data:

networks:
  development:
    driver: bridge
